# Site settings
author: James Cox
title: A Newbie to Ruby
header-img: img/home-bg.png
email: jamesncox@yahoo.com
copyright_name: James Cox
description: > # this means to ignore newlines until "baseurl:"
  I'm going to learn coding; this is what that looks like....
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: MemRook
github_username:  jamesncox

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
